# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f53b108c94edf3f863a15212942f1ffbff348bfcf50d45ae49498a3795f13e9fede721dd12d8510fee479b8b8e260ff3e5661df60c74372a4e9f426f6796f6ee

test:
  secret_key_base: c4beb7f17765822b42c04d99e335d6307f3968f1685f48c4b624072bc388f0db1dc69feefcd0820f0f828f2e5de791544db34fb2bef074271878088244470487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
